### ISSUE TITLE
Reindexing only valid with uniquely valued Index objects

### ISSUE THREAD

**Issue by KasperH2** [ACEnglish/truvari#119]
Hi 
I'm using truvari bench on lumpy, delly, manta and cnvnator calls.       
However, on lumpy output I get this:

```
2022-05-04 13:59:41,401 [CRITICAL] Unknown Number (2) for CIEND. Skipping.
2022-05-04 13:59:41,401 [CRITICAL] Unknown Number (2) for CIEND95. Skipping.
2022-05-04 13:59:41,401 [CRITICAL] Unknown Number (2) for CIPOS. Skipping.
2022-05-04 13:59:41,401 [CRITICAL] Unknown Number (2) for CIPOS95. Skipping.
2022-05-04 13:59:41,420 [CRITICAL] Unknown Number (2) for CIEND. Skipping.
2022-05-04 13:59:41,420 [CRITICAL] Unknown Number (2) for CIEND95. Skipping.
2022-05-04 13:59:41,420 [CRITICAL] Unknown Number (2) for CIPOS. Skipping.
2022-05-04 13:59:41,420 [CRITICAL] Unknown Number (2) for CIPOS95. Skipping.
Traceback (most recent call last):
  File "/usr/local/bin/truvari", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/truvari/__main__.py", line 85, in main
    TOOLS[args.cmd](args.options)
  File "/usr/local/lib/python3.8/dist-packages/truvari/bench.py", line 808, in bench_main
    make_giabreport(args, outputs["stats_box"])
  File "/usr/local/lib/python3.8/dist-packages/truvari/giab_report.py", line 36, in make_giabreport
    truvari.vcf2df.vcf2df_main(["-i", "-f", "-b", args.output, out_df])
  File "/usr/local/lib/python3.8/dist-packages/truvari/vcf2df.py", line 411, in vcf2df_main
    out = pd.concat(all_dfs)
  File "/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/concat.py", line 360, in concat
    return op.get_result()
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/concat.py", line 591, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py", line 3721, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects
```

What might cause this error? I ran the vcfs through the usable_vcf.py script and only see
`2022-05-04 14:25:00,760 [DEBUG] b'Warning: Duplicate entries, for example chr1:121756074\n'`

Removing these duplicate entries does not seem to fix it and they are not a problem for other vcf files that are not from lumpy. Any suggestion?
Thanks for your help.

**Comment by ACEnglish** [comment]
Could you please provide a lumpy vcf so that I can recreate this error. This is an error with pandas that appears to have a [solution](https://stackoverflow.com/questions/35084071/concat-dataframe-reindexing-only-valid-with-uniquely-valued-index-objects), but I need example data to implement a fix.

**Comment by ACEnglish** [comment]
Marking ticket as abandoned. Please reopen if you have a follow-up
