### ISSUE TITLE
error from collapse function : TypeError: invalid value for Integer format

### ISSUE THREAD

**Issue by yaowei2010** [ACEnglish/truvari#139]
**Version** :  3.5.0

**Describe the bug** : 

I used the collapse function to work on a merge.vcf.gz (with three samples) to test this function.
And the command is 

```
truvari collapse -i merge.vcf.gz -o truvari_merge.vcf -c truvari_collapsed.vcf -f <#ref>/hg19.fa --debug
```

I got the bug like this:

-----------------------------------------------------------------
2023-01-06 17:36:09,181 [DEBUG] Comparing chunk [<pysam.libcbcf.VariantRecord object at 0x7f4f9ba69190>, <pysam.libcbcf.VariantRecord object at 0x7f4f9ba691c0>]
2023-01-06 17:36:09,182 [DEBUG] Collapsing 1:90046-90283.C
Traceback (most recent call last):
  File "/home/bioinfo/miniconda3/bin/truvari", line 8, in <module>
    sys.exit(main())
  File "/home/bioinfo/miniconda3/lib/python3.9/site-packages/truvari/__main__.py", line 95, in main
    TOOLS[args.cmd](args.options)
  File "/home/bioinfo/miniconda3/lib/python3.9/site-packages/truvari/collapse.py", line 426, in collapse_main
    output_writer(call, outputs)
  File "/home/bioinfo/miniconda3/lib/python3.9/site-packages/truvari/collapse.py", line 390, in output_writer
    annotate_entry(entry, len(collapsed), consol_cnt,
  File "/home/bioinfo/miniconda3/lib/python3.9/site-packages/truvari/collapse.py", line 232, in annotate_entry
    entry.info["CollapseId"] = match_id
  File "pysam/libcbcf.pyx", line 2623, in pysam.libcbcf.VariantRecordInfo.__setitem__
  File "pysam/libcbcf.pyx", line 707, in pysam.libcbcf.bcf_info_set_value
  File "pysam/libcbcf.pyx", line 612, in pysam.libcbcf.bcf_check_values
TypeError: invalid value for Integer format
-----------------------------------------------------------------

**To Reproduce** : 
Steps/Commands to reproduce the behavior with stdout/stderr log lines when reasonable/necessary.

```
truvari collapse -i merge.vcf.gz -o truvari_merge.vcf -c truvari_collapsed.vcf -f <#ref>/hg19.fa --debug
```

**Expected behavior** : 

**Example Data** : 
I merged three data from TruvariData set: HG00096.vcf.gz, HG00171.vcf.gz, and HG00512.vcf.gz.
And I have tested two of them with bench function in truvari. It worked.
The reference genome is hg19 version.

**Additional context** :

**Comment by ACEnglish** [comment]
Hello,

I believe I've seen this error before. When I've encountered it, there was a problem with the headers. The problem is that  older versions of Truvari collapse (~v3.1?) added the annotation `##INFO=<ID=CollapseId,Number=1,Type=Integer,` However, to make the annotation more informative for tracing chunks/pairs, it needed to be updated to a string `##INFO=<ID=CollapseId,Number=1,Type=String,` (see [wiki](https://github.com/ACEnglish/truvari/wiki/MatchIds)). 

If my guess is correct, your input VCFs `HG00096.vcf.gz`, `HG00171.vcf.gz`, and `HG00512.vcf.gz` already have the `CollapseId` defined in the header as  Integer type and pysam won't overwrite existing header lines.

Please try to remove CollapseId from your input VCF with:
```bash
bcftools annotate -x INFO/CollapseId  merge.vcf.gz -O z -o merge.fixed.vcf.gz
```

Then re-run collapse and let me know if that works.

Have a great day,
~/Adam
