### ISSUE TITLE
Error when runnig `truvari bench`

### ISSUE THREAD

**Issue by jyw-atgithub** [ACEnglish/truvari#180]
Hi @ACEnglish , 
I used sim-it to simulate SVs and reads. Then, the following command was used:

 `ruvari bench --pctseq 0 -b Hifi_60x_0.999_1.sort.vcf.gz -c Hifi_60x_0.999_1.tru_con.sort.vcf.gz -f dmel-all-chromosome-r6.49.fasta -o /....../truvari_bench/Hifi_60x_0.999_1`

I have checked that the format of input vcf.gz files were accepted by bcftools. But, `truvari bench` kept reporting error messages.
Could you please provide some ideas or suggestions to resolve this? Thank you  **:)**

```
2023-12-12 04:53:38,965 [WARNING] Excluding 1863 contigs present in comparison calls header but not baseline calls.
[E::vcf_format] Invalid BCF, the INFO tag id=14 is too large at 2L:61980
Traceback (most recent call last):
  File "/data/homezvol2/jenyuw/.local/bin/truvari", line 8, in <module>
    sys.exit(main())
  File "/data/homezvol2/jenyuw/.local/lib/python3.10/site-packages/truvari/__main__.py", line 102, in main
    TOOLS[args.cmd](args.options)
  File "/data/homezvol2/jenyuw/.local/lib/python3.10/site-packages/truvari/bench.py", line 802, in bench_main
    output = m_bench.run()
  File "/data/homezvol2/jenyuw/.local/lib/python3.10/site-packages/truvari/bench.py", line 565, in run
    output.write_match(match)
  File "/data/homezvol2/jenyuw/.local/lib/python3.10/site-packages/truvari/bench.py", line 406, in write_match
    self.out_vcfs["tpb"].write(match.base)
  File "pysam/libcbcf.pyx", line 4482, in pysam.libcbcf.VariantFile.write
  File "pysam/libcbcf.pyx", line 4519, in pysam.libcbcf.VariantFile.write
OSError: [Errno 22] b'Invalid argument'
```

#### part of the  "base" vcf

![image](https://github.com/ACEnglish/truvari/assets/53656868/5c87e588-9542-4d23-a36c-d2f20c865447)

**Comment by ACEnglish** [comment]
The base SVs don't have an `INFO/END` defined. 

For example, if I take the first entry from your base VCF:
```
##fileformat=VCFv4.0
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=99991122
##contig=<ID=2L,length=23513712>
##contig=<ID=2R,length=25286936>
##contig=<ID=3L,length=28110227>
##contig=<ID=3R,length=32079331>
##contig=<ID=4,length=1348131>
##contig=<ID=X,length=23542271>
##contig=<ID=Y,length=3667352>
##ALT=<ID=INS,Description=Insertion of novel sequence relative to the reference>
##ALT=<ID=DEL,Description=Deletion relative to the reference>
##ALT=<ID=DUP,Description=Region of elevated copy number relative to the reference>
##ALT=<ID=INV,Description=Inversion of reference sequence>
##ALT=<ID=BND,Description=Breakend of translocation>
##INFO=<ID=SVTYPE,Number=1,Type=String,Description=Type of structural variant>
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description=Difference in length between REF and ALT alleles>
##FORMAT=<ID=GT,Number=1,Type=String,Description=Genotype>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Hifi_60x_0.999_1_cute
2L	61980	idINS61980	a	<INS>	30	PASS	SVTYPE=INS;SVLEN=89	GT	1/1
```

And run it through htslib:
```python
import pysam
import sys

v = pysam.VariantFile(sys.argv[1])
o = pysam.VariantFile("delme.vcf", 'w', header=v.header)

for e in v:
    o.write(e)
```

I get the error:
```
[E::vcf_format] Invalid BCF, the INFO tag id=4 is too large at 2L:61980
Traceback (most recent call last):
  File "/Users/english/code/truvari/tickets/long/dumb.py", line 8, in <module>
    o.write(e)
  File "pysam/libcbcf.pyx", line 4482, in pysam.libcbcf.VariantFile.write
  File "pysam/libcbcf.pyx", line 4519, in pysam.libcbcf.VariantFile.write
OSError: [Errno 22] b'Invalid argument'
```

But when I add `INFO/END`:
```
##fileformat=VCFv4.0
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=99991122
##contig=<ID=2L,length=23513712>
##contig=<ID=2R,length=25286936>
##contig=<ID=3L,length=28110227>
##contig=<ID=3R,length=32079331>
##contig=<ID=4,length=1348131>
##contig=<ID=X,length=23542271>
##contig=<ID=Y,length=3667352>
##ALT=<ID=INS,Description=Insertion of novel sequence relative to the reference>
##ALT=<ID=DEL,Description=Deletion relative to the reference>
##ALT=<ID=DUP,Description=Region of elevated copy number relative to the reference>
##ALT=<ID=INV,Description=Inversion of reference sequence>
##ALT=<ID=BND,Description=Breakend of translocation>
##INFO=<ID=SVTYPE,Number=1,Type=String,Description=Type of structural variant>
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description=Difference in length between REF and ALT alleles>
##INFO=<ID=END,Number=1,Type=Integer,Description=End position>
##FORMAT=<ID=GT,Number=1,Type=String,Description=Genotype>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Hifi_60x_0.999_1_cute
2L	61980	idINS61980	a	<INS>	30	PASS	SVTYPE=INS;SVLEN=89;END=61981	GT	1/1
```
I do not get the error.

**Comment by jyw-atgithub** [comment]
**Thank you!!**
