### ISSUE TITLE
TypeError,  'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by jyw-atgithub** [ACEnglish/truvari#187]
Hi @ACEnglish ,
I am using the stable release v4.2 of Truvari. I am trying to `collapse` the structural variants from two callers of one sample.
`bcftools merge -m none` worked well. However, I encountered an error message as following. Truvari did output something but it was incomplete. Thus, I inspected the input file were it stopped in the output and nothing abnormal was noticed. Did miss anything? Thank you!

```
2024-01-23 03:31:59,576 [WARNING] Unresolved SVs (e.g. ALT=<DEL>) are filtered when `--pctseq != 0`
Traceback (most recent call last):
  File "/data/homezvol2/jenyuw/.local/bin/truvari", line 8, in <module>
    sys.exit(main())
  File "/data/homezvol2/jenyuw/.local/lib/python3.10/site-packages/truvari/__main__.py", line 102, in main
    TOOLS[args.cmd](args.options)
  File "/data/homezvol2/jenyuw/.local/lib/python3.10/site-packages/truvari/collapse.py", line 768, in collapse_main
    for call in itertools.chain.from_iterable(map(m_collap, even_smaller_chunks)):
  File "/data/homezvol2/jenyuw/.local/lib/python3.10/site-packages/truvari/collapse.py", line 92, in collapse_chunk
    remaining_calls = sorted(chunk_dict['base'], key=matcher.sorter)
  File "/data/homezvol2/jenyuw/.local/lib/python3.10/site-packages/truvari/collapse.py", line 385, in sort_maxqual
    if b1.qual < b2.qual:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

The command was:

```bash
truvari collapse --intra -k maxqual --sizemax 200000000 \
-i ${con_SVs}/${name}.asm-2.vcf.gz \
-c ${con_SVs}/${name}.asm-2.tru_collapsed.vcf -f ${ref_genome} |\
bcftools sort -m 2G |bgzip -@ ${nT} > ${con_SVs}/${name}.asm-2.tru_con.sort.vcf.gz
```

Here is the input vcf file. and the output.  
input=[A1_CLR.asm-2.vcf.gz](https://github.com/jyw-atgithub/SV-evolution/blob/main/temp/A1_CLR.asm-2.vcf.gz)
output=[A1_CLR.asm-2.tru_con.sort.vcf.gz](https://github.com/jyw-atgithub/SV-evolution/blob/main/temp/A1_CLR.asm-2.tru_con.sort.vcf.gz)
[Link](https://github.com/jyw-atgithub/SV-evolution/tree/main/temp)

**Comment by jyw-atgithub** [comment]
Thank you for the fast response. It is resolved after I manually altered the quality scores in to 30.
