### ISSUE TITLE
 Truvari Collapse error

### ISSUE THREAD

**Issue by Flooooooooooooower** [ACEnglish/truvari#218]
Dear Prof.
Thank you for inventing such a useful software. However, I encountered a "Thr prefix REF error" before using bcftools merge, so I used bcftools norm -c s. After that, I experienced the following log error with truvari collapse. I am unable to resolve this issue and would appreciate your assistance in clarifying it for me.
2024-07-27 22:55:05,675 [INFO] Truvari v4.0.0
2024-07-27 22:55:05,675 [INFO] Command /usr/local/bin/truvari collapse -i re_merge.vcf.gz -o merge/truvari_merge.vcf -c merge/truvari_collapsed.vcf --reference /home/jiaoh/01.Reference/Human_GRC
2024-07-27 22:55:05,675 [INFO] Params:
{
    "input": "re_merge.vcf.gz",
    "output": "merge/truvari_merge.vcf",
    "collapsed_output": "merge/truvari_collapsed.vcf",
    "reference": "/home/jiaoh/01.Reference/Human_GRCh37/GCF_000001405.25_GRCh37.p13_genomic.fa",
    "keep": "first",
    "debug": false,
    "refdist": 500,
    "pctseq": 0.95,
    "minhaplen": 50,
    "pctsize": 0.95,
    "pctovl": 0.0,
    "typeignore": false,
    "use_lev": false,
    "hap": false,
    "chain": false,
    "no_consolidate": true,
    "null_consolidate": null,
    "sizemin": 50,
    "sizemax": 50000,
    "passonly": false,
    "chunksize": 500,
    "bSample": null,
    "cSample": null,
    "sizefilt": 50,
    "no_ref": false
}
Traceback (most recent call last):
  File "/usr/local/bin/truvari", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/truvari/__main__.py", line 102, in main
    TOOLS[args.cmd](args.options)
  File "/usr/local/lib/python3.10/dist-packages/truvari/collapse.py", line 420, in collapse_main
    for call in itertools.chain.from_iterable(map(collapse_chunk, chunks)):
  File "/usr/local/lib/python3.10/dist-packages/truvari/matching.py", line 293, in chunker
    if len(entry.alts) > 1:
TypeError: object of type 'NoneType' has no len()

**Comment by ACEnglish** [comment]
This was a bug in v4.0.0 that was fixed as of v4.1.0. Upgrading to the latest version, v4.2.2, should prevent the error.
