### ISSUE TITLE
Changing sizemax for Truvari collapse triggering a pysam KeyError

### ISSUE THREAD

**Issue by vondant** [ACEnglish/truvari#234]
Hi, I was altering the max size of the variants for Truvari from 50kb to 10mb, however when doing so I was given a PySam KeyError.
I am unclear as to why GT is being used when sizemax is changed.
```
{
    "reference": null,
    "keep": "first",
    "bed": null,
    "gt": "off",
    "intra": false,
    "median_info": false,
    "debug": false,
    "refdist": 500,
    "pctseq": 0.0,
    "minhaplen": 50,
    "pctsize": 0.95,
    "pctovl": 0.0,
    "typeignore": false,
    "hap": false,
    "chain": false,
    "no_consolidate": true,
    "null_consolidate": null,
    "sizemin": 50,
    "sizemax": 10000000,
    "passonly": false,
    "chunksize": 500,
    "bSample": null,
    "cSample": null,
    "sizefilt": 50,
    "no_ref": false
}
Traceback (most recent call last):
  File "/newhome/vondant/anaconda3/bin/truvari", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/newhome/vondant/anaconda3/lib/python3.12/site-packages/truvari/__main__.py", line 105, in main
    TOOLS[args.cmd](args.options)
  File "/newhome/vondant/anaconda3/lib/python3.12/site-packages/truvari/collapse.py", line 888, in collapse_main
    for call in itertools.chain.from_iterable(map(m_collap, even_smaller_chunks)):
  File "/newhome/vondant/anaconda3/lib/python3.12/site-packages/truvari/collapse.py", line 176, in collapse_chunk
    edited_entry, collapse_cnt = collapse_into_entry(
                                 ^^^^^^^^^^^^^^^^^^^^
  File "/newhome/vondant/anaconda3/lib/python3.12/site-packages/truvari/collapse.py", line 213, in collapse_into_entry
    m_gt = truvari.get_gt(entry.samples[sample]["GT"])
                          ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "pysam/libcbcf.pyx", line 3541, in pysam.libcbcf.VariantRecordSample.__getitem__
  File "pysam/libcbcf.pyx", line 813, in pysam.libcbcf.bcf_format_get_value
KeyError: 'invalid FORMAT: GT'

```

**Comment by ACEnglish** [comment]
The `--sizemax` is indirectly causing this error because there are variants larger than the default `--sizemax=50000` that you're now analyzing. This error is telling us that one of those ≥50kbp SVs does not have a GT format field. Truvari expects GT to be present in the VCF line, even if it is a null value (e.g. `GT ./.`). You'll need to add GT to all your VCF entries.
