### ISSUE TITLE
Error running the `truvari ga4gh` command after `truvari refine`

### ISSUE THREAD

**Issue by rickymagner** [ACEnglish/truvari#237]
**Version** : 

`Truvari v4.3.1`

**Describe the bug** : 

I am getting a stacktrace when running `truvari ga4gh` on the outputs of `truvari refine`. Here is the sequence of commands run:
```
        truvari bench \
            --reference ref.fasta \
            --includebed eval.bed \
            --base base.vcf.gz \
            --comp comp.vcf.gz \
            --output outputs \
            --passonly \
            --pick ac \
            --dup-to-ins

        truvari refine \
            --reference ref.fasta \
            --regions outputs/candidate.refine.bed \
            --recount \
            --use-region-coords \
            --use-original-vcfs \
            --align mafft \
            outputs

        truvari ga4gh \
           --input outputs \
           --output outputs/combined_result \
           --with-refine
```
The first two complete successfully, but the last produces the following:

```
truvari ga4gh --input data/outputs --output data/combined_result --with-refine
2024-10-14 16:49:28,558 [INFO] Consolidating VCFs
Traceback (most recent call last):
  File "/usr/local/bin/truvari", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/truvari/__main__.py", line 105, in main
    TOOLS[args.cmd](args.options)
  File "/usr/local/lib/python3.10/dist-packages/truvari/make_ga4gh.py", line 190, in make_ga4gh_main
    parse_bench_dir(args.input, t_vcf, q_vcf, tree=refine_tree, is_refined=False)
  File "/usr/local/lib/python3.10/dist-packages/truvari/make_ga4gh.py", line 101, in parse_bench_dir
    n_entry = move_record(entry, out_vcf, samp)
  File "/usr/local/lib/python3.10/dist-packages/truvari/make_ga4gh.py", line 82, in move_record
    ret.samples[0][k] = v
  File "pysam/libcbcf.pyx", line 3544, in pysam.libcbcf.VariantRecordSample.__setitem__
  File "pysam/libcbcf.pyx", line 876, in pysam.libcbcf.bcf_format_set_value
  File "pysam/libcbcf.pyx", line 600, in pysam.libcbcf.bcf_check_values
TypeError: values expected to be 2-tuple, given len=1
```

I'm not sure what assumptions the tool is making about the VCF, but it seems like it's expecting something in the INFO fields, etc from the outputs of the previous two commands. Here are the contents of the `outputs` dir:
```
> ls data/outputs
candidate.refine.bed  fn.vcf.gz.tbi  fp.vcf.gz.tbi  params.json         phab.output.vcf.gz.tbi  refine.log.txt              refine.regions.txt           summary.json    tp-base.vcf.gz.tbi  tp-comp.vcf.gz.tbi
fn.vcf.gz             fp.vcf.gz      log.txt        phab.output.vcf.gz  phab_bench              refine.region_summary.json  refine.variant_summary.json  tp-base.vcf.gz  tp-comp.vcf.gz
```

The input base vcf is phased, and the comp vcf is phased using hiphase beforehand, as required by the `refine` command. Can anyone say more about what might be happening in the stacktrace blocks for `ga4gh` so I can try debugging the files themselves? Or is there a bug in how the outputs are being written for the previous truvari commands? Thanks

**Comment by ACEnglish** [comment]
Hello,

Your commands look fine, so we're definitely dealing with something to do with the VCFs. The code where the error is happening is trying to consolidate the baseline and comparison VCFs. This specific error (2-tuple, given len=1) suggests that the two VCFs have different FORMAT tag definitions which are incompatible. I can't tell you which FORMAT field is the problem with the information provided. But you'll be looking for something like:
```
base VCF:
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Read depth per allele">
comp VCF:
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Read depth per allele">
```
One VCF is specifying that the number of values in the format field should be 2. So `Number=R` or maybe `Number=A` while the other allows a variable number of values (likely `Number=.`) and holds only 1 value (thus `given len=1`). 

If you find incompatible FORMAT fields matching this description, the easiest solution would probably be to redefine the header tags to all `Number=.`, which should prevent pysam from caring about the exact number of values in the field.

Let me know if that helps or you need more assistance.

**Comment by rickymagner** [comment]
Hi Adam, thanks for getting back. You're right that the AD field was causing an issue, since using `bcftools annotate -x INFO/AD` before the commands above cleared it up. But I think this might still qualify as a bug since my comparison VCF didn't contain any AD field while the truth did. I would expect in the case that one of the VCFs has an annotation the other doesn't, the output would still be generated properly. I'd imagine something like assuming `Number=.` as the default for missing annotations, which would trigger the issue you outlined there.

**Comment by ACEnglish** [comment]
Thanks for the follow up. I didn't consider this possibility, but it totally makes sense how it happens. I believe I have some methods I can reuse to make this work better. I'll put it on the development roadmap as yet another feature for a VCF edge case.

**Comment by yeeus** [comment]
I also met a similar problem:
```
(truvari5) [chenquanyu@cu13 new_compare]$ truvari refine -a mafft -t 32 -f ~/rawdata/CHM13/ref/CHM13v2.fasta bench
2026-05-04 16:46:49,519 [INFO] Truvari v5.3.0
2026-05-04 16:46:49,519 [INFO] Command /share/home/zhanglab/user/chenquanyu/mambaforge/envs/truvari5/bin/truvari refine -a mafft -t 32 -f /share/home/zhanglab/user/chenquanyu/rawdata/CHM13/ref/CHM13v2.fasta bench
2026-05-04 16:46:49,519 [INFO] Params:
{
    "benchdir": "bench",
    "align": "mafft",
    "use_original_vcfs": false,
    "write_phab": false,
    "threads": 32,
    "buffer": 100,
    "reference": "/share/home/zhanglab/user/chenquanyu/rawdata/CHM13/ref/CHM13v2.fasta",
    "regions": "bench/candidate.refine.bed",
    "coords": "R",
    "subset": false,
    "mafft_params": "--auto --thread 1",
    "debug": false
}
2026-05-04 16:46:49,520 [INFO] Setting up regions
2026-05-04 16:46:49,788 [INFO] 31450 --regions loaded
2026-05-04 16:46:49,788 [INFO] Extending the regions by 100 bases
2026-05-04 16:47:15,635 [INFO] 7099 regions to be refined
2026-05-04 16:47:15,772 [INFO] Preparing reference/regions
2026-05-04 16:47:17,568 [INFO] Building haplotypes
2026-05-04 16:47:22,898 [INFO] Harmonizing variants
2026-05-04 20:08:21,854 [INFO] Running bench
2026-05-04 20:08:23,974 [INFO] Including 7099 bed regions
2026-05-04 20:09:36,684 [INFO] Zipped 1115440 variants Counter({'base': 557720, 'comp': 557720})
2026-05-04 20:09:36,685 [INFO] 6770 chunks of 1115440 variants Counter({'__filtered': 1077239, 'comp': 22854, 'base': 15347})
Traceback (most recent call last):
  File "/share/home/zhanglab/user/chenquanyu/mambaforge/envs/truvari5/bin/truvari", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/share/home/zhanglab/user/chenquanyu/mambaforge/envs/truvari5/lib/python3.11/site-packages/truvari/__main__.py", line 105, in main
    TOOLS[args.cmd](args.options)
  File "/share/home/zhanglab/user/chenquanyu/mambaforge/envs/truvari5/lib/python3.11/site-packages/truvari/refine.py", line 413, in refine_main
    output = make_ga4gh(args.benchdir,
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/home/zhanglab/user/chenquanyu/mambaforge/envs/truvari5/lib/python3.11/site-packages/truvari/make_ga4gh.py", line 277, in make_ga4gh
    output.pull_from_dir(input_dir, regions[mask], within=True, force_tp=True,
  File "/share/home/zhanglab/user/chenquanyu/mambaforge/envs/truvari5/lib/python3.11/site-packages/truvari/make_ga4gh.py", line 191, in pull_from_dir
    self.stats['TP-base'] += self.pull_annotate(puller(vcf),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/home/zhanglab/user/chenquanyu/mambaforge/envs/truvari5/lib/python3.11/site-packages/truvari/make_ga4gh.py", line 158, in pull_annotate
    n_entry = entry.move_record(out_vcf, [f_sample], [t_sample])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/home/zhanglab/user/chenquanyu/mambaforge/envs/truvari5/lib/python3.11/site-packages/truvari/variant_record.py", line 601, in move_record
    ret = out_vcf.new_record(contig=self.contig, start=self.start, stop=self.stop, alleles=self.alleles,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pysam/libcbcf.pyx", line 4478, in pysam.libcbcf.VariantFile.new_record
  File "pysam/libcbcf.pyx", line 2111, in pysam.libcbcf.VariantHeader.new_record
  File "pysam/libcbcf.pyx", line 2796, in pysam.libcbcf.VariantRecordInfo.update
  File "pysam/libcbcf.pyx", line 2619, in pysam.libcbcf.VariantRecordInfo.__setitem__
  File "pysam/libcbcf.pyx", line 704, in pysam.libcbcf.bcf_info_set_value
  File "pysam/libcbcf.pyx", line 600, in pysam.libcbcf.bcf_check_values
TypeError: values expected to be 2-tuple, given len=10
```

At the beginning, I thought this was caused by the format/info tag, which was the same in my case, however.
So what's the reason?

Best wishes!
